apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-workers-pdb
  namespace: suspensionlab-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: suspensionlab
      component: workers
