"use client";
import { useState, useCallback } from "react";
import { FileDown, Loader2 } from "lucide-react";

interface PDFExportProps {
  captureId: string;    // id of the DOM element to capture
  fileName?: string;    // output filename without .pdf
  title?: string;
  params?: Record<string, unknown>;
  metrics?: Record<string, unknown>;
}

export default function PDFExport({
  captureId, fileName = "suspensionlab-report", title = "SuspensionLab Report",
  params, metrics,
}: PDFExportProps) {
  const [exporting, setExporting] = useState(false);

  const handleExport = useCallback(async () => {
    setExporting(true);
    try {
      // Dynamic imports — keeps the 1.4 MB jspdf bundle out of the initial page load
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import("jspdf"),
        import("html2canvas"),
      ]);

      const element = document.getElementById(captureId);
      if (!element) throw new Error(`Element #${captureId} not found`);

      const canvas  = await html2canvas(element, {
        backgroundColor: "#0d0d0f",
        scale: 2,          // 2× for retina-quality output
        useCORS: true,
        logging: false,
      });

      const pdf     = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
      const pageW   = pdf.internal.pageSize.getWidth();
      const pageH   = pdf.internal.pageSize.getHeight();

      // ── Header ──────────────────────────────────────────────────────────
      pdf.setFillColor(13, 13, 15);
      pdf.rect(0, 0, pageW, pageH, "F");

      // Logo bar
      pdf.setFillColor(20, 20, 22);
      pdf.rect(0, 0, pageW, 18, "F");
      pdf.setTextColor(242, 169, 0);
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.text("SuspensionLab Pro", 10, 12);
      pdf.setTextColor(100, 100, 100);
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      pdf.text(title, pageW / 2, 12, { align: "center" });
      pdf.text(new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }), pageW - 10, 12, { align: "right" });

      // ── Params table (left column) ────────────────────────────────────
      let y = 24;
      if (params && Object.keys(params).length) {
        pdf.setTextColor(100, 100, 100);
        pdf.setFontSize(7);
        pdf.setFont("helvetica", "bold");
        pdf.text("INPUT PARAMETERS", 10, y);
        y += 5;
        pdf.setFont("helvetica", "normal");
        Object.entries(params).slice(0, 12).forEach(([k, v]) => {
          pdf.setTextColor(80, 80, 80);
          pdf.text(`${k}:`, 10, y);
          pdf.setTextColor(200, 200, 200);
          pdf.text(String(v), 48, y);
          y += 4.5;
        });
      }

      // ── Metrics table (right column) ──────────────────────────────────
      let my = 24;
      if (metrics && Object.keys(metrics).length) {
        pdf.setTextColor(100, 100, 100);
        pdf.setFontSize(7);
        pdf.setFont("helvetica", "bold");
        pdf.text("KEY PERFORMANCE INDICATORS", pageW / 2 + 4, my);
        my += 5;
        pdf.setFont("helvetica", "normal");
        Object.entries(metrics).slice(0, 12).forEach(([k, v]) => {
          pdf.setTextColor(80, 80, 80);
          pdf.text(`${k}:`, pageW / 2 + 4, my);
          pdf.setTextColor(242, 169, 0);
          pdf.text(String(typeof v === "number" ? v.toFixed(4) : v), pageW - 10, my, { align: "right" });
          my += 4.5;
        });
      }

      // ── Simulation screenshot ─────────────────────────────────────────
      const imgData = canvas.toDataURL("image/jpeg", 0.92);
      const plotTop = Math.max(y, my) + 4;
      const imgH    = pageH - plotTop - 10;
      const imgW    = (canvas.width / canvas.height) * imgH;
      const imgX    = (pageW - imgW) / 2;
      pdf.addImage(imgData, "JPEG", imgX, plotTop, imgW, imgH);

      // ── Footer ───────────────────────────────────────────────────────
      pdf.setFillColor(13, 13, 15);
      pdf.rect(0, pageH - 8, pageW, 8, "F");
      pdf.setTextColor(50, 50, 50);
      pdf.setFontSize(7);
      pdf.text("Generated by SuspensionLab Pro — suspensionlab.io", pageW / 2, pageH - 3, { align: "center" });

      pdf.save(`${fileName}-${Date.now()}.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
      alert("PDF export failed. Try the browser Print (Ctrl+P) as a fallback.");
    } finally {
      setExporting(false);
    }
  }, [captureId, fileName, title, params, metrics]);

  return (
    <button onClick={handleExport} disabled={exporting}
      className="flex items-center gap-1.5 px-3 py-1.5 bg-[#141416] border border-[#252525]
        hover:bg-[#1e1e20] rounded-lg text-xs font-medium transition-colors disabled:opacity-40">
      {exporting
        ? <><Loader2 size={13} className="animate-spin" /> Generating PDF…</>
        : <><FileDown size={13} /> Export PDF</>}
    </button>
  );
}
