"""Drop tier column

Revision ID: 8ff4d3e48527
Revises: 8f6fb1bdcda6
Create Date: 2026-06-09 01:29:50.826444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff4d3e48527'
down_revision: Union[str, Sequence[str], None] = '8f6fb1bdcda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tier')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.VARCHAR(length=20), nullable=False, server_default='FREE'))

    # ### end Alembic commands ###

    # ### end Alembic commands ###
