"""Add Collaboration Hub

Revision ID: d713c8804400
Revises: 8ff4d3e48527
Create Date: 2026-06-09 01:41:03.543852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd713c8804400'
down_revision: Union[str, Sequence[str], None] = '8ff4d3e48527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('params_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_team_id'), ['team_id'], unique=False)

    op.create_table('session_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chart_region', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_comments_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_jobs_session_id_sessions', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_jobs_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_session_id_sessions', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_session_id'))
        batch_op.drop_column('session_id')

    with op.batch_alter_table('session_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_comments_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_comments_id'))

    op.drop_table('session_comments')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_team_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_owner_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_id'))

    op.drop_table('sessions')
    # ### end Alembic commands ###
