"""initial_schema

Revision ID: 7e44398ceef5
Revises: 
Create Date: 2026-06-06 03:12:18.167842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e44398ceef5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('idx_user_active_jobs', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)
        batch_op.create_index('ix_jobs_started_at', ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_jobs_user_status', ['user_id', 'status'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_slug'), ['slug'], unique=True)

    op.create_table('vehicle_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_profiles_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_profiles_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_api_key', ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_stripe_cust', ['stripe_customer_id'], unique=False)
        batch_op.create_index('ix_users_team_id', ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_team_id')
        batch_op.drop_index('ix_users_stripe_cust')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('ix_users_api_key')

    op.drop_table('users')
    with op.batch_alter_table('vehicle_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_profiles_team_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_profiles_name'))
        batch_op.drop_index(batch_op.f('ix_vehicle_profiles_id'))

    op.drop_table('vehicle_profiles')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_slug'))

    op.drop_table('teams')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_user_status')
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index('ix_jobs_started_at')
        batch_op.drop_index(batch_op.f('ix_jobs_id'))
        batch_op.drop_index('idx_user_active_jobs')

    op.drop_table('jobs')
    # ### end Alembic commands ###
