apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: suspensionlab-prod
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.secrets.stripeWebhookSecret | b64enc | quote }}
