from fastapi import APIRouter, Depends, HTTPException, Response
import datetime

from suspensionlab.shared.models import SimulateRequest, PlanTier
from suspensionlab.backend.security.auth import require_plan
from suspensionlab.physics.quarter_car import QuarterCarParams, RoadProfile, run_quarter_car_analysis

router = APIRouter(prefix="/reports", tags=["ISO Compliance Report Engine"])

@router.post("/iso2631", response_class=Response)
async def generate_iso_report(
    request_data: SimulateRequest,
    user: dict = Depends(require_plan(PlanTier.ENTERPRISE))
):
    """
    Generate an official HTML standalone ISO 2631-1 Benchmark Report for procurement.
    """
    import html

    # 1. Run simulation to get Wk weighted acceleration
    params = QuarterCarParams(**request_data.params.model_dump())
    profile = RoadProfile(**request_data.profile.model_dump())
    res = run_quarter_car_analysis(params, profile)
    
    wk_rms = res.rms_body_accel_wk
    comfort_str = res.comfort_rating
    
    # ISO classification color coding
    if wk_rms < 0.315:
        status_color = "#2e7d32" # Green
    elif wk_rms < 0.63:
        status_color = "#f57f17" # Orange
    else:
        status_color = "#c62828" # Red
        
    date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    safe_email = html.escape(user.get('email', 'Enterprise User'))

    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>ISO 2631-1 Benchmark Report</title>
        <style>
            body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; margin: 40px; color: #333; }}
            .header {{ border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 30px; }}
            .logo {{ font-size: 24px; font-weight: bold; color: #1a73e8; }}
            h1 {{ font-size: 20px; text-transform: uppercase; }}
            .section {{ margin-bottom: 30px; }}
            .metrics-table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
            .metrics-table th, .metrics-table td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
            .metrics-table th {{ background-color: #f5f5f5; width: 50%; }}
            .status-box {{ padding: 20px; background-color: {status_color}; color: white; text-align: center; font-size: 18px; font-weight: bold; border-radius: 4px; margin-top: 20px; }}
            .footer {{ margin-top: 50px; font-size: 12px; color: #777; border-top: 1px solid #ddd; padding-top: 10px; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="header">
            <div class="logo">SuspensionLab PRO</div>
            <h1>ISO 2631-1 Compliance Report</h1>
            <p><strong>Date Generated:</strong> {date_str}</p>
            <p><strong>Generated By:</strong> {safe_email}</p>
        </div>

        <div class="section">
            <h2>1. Vehicle Parameters (Quarter Car)</h2>
            <table class="metrics-table">
                <tr><th>Sprung Mass (m_s)</th><td>{params.m_s} kg</td></tr>
                <tr style="background-color: #fdfdfd;"><th>Unsprung Mass (m_u)</th><td>{params.m_u} kg</td></tr>
                <tr><th>Suspension Stiffness (k_s)</th><td>{params.k_s} N/m</td></tr>
                <tr style="background-color: #fdfdfd;"><th>Suspension Damping (c_s)</th><td>{params.c} N.s/m</td></tr>
                <tr><th>Tire Stiffness (k_t)</th><td>{params.k_t} N/m</td></tr>
            </table>
        </div>

        <div class="section">
            <h2>2. ISO 2631-1 Whole-Body Vibration Assessment</h2>
            <p>The step-response transient was filtered using the principal frequency weighting Wk as specified by ISO 2631-1 for vertical seat vibration.</p>
            <table class="metrics-table">
                <tr><th>Raw RMS Acceleration</th><td>{res.rms_body_accel:.4f} m/s²</td></tr>
                <tr style="background-color: #fdfdfd;"><th>Wk-Weighted RMS Acceleration</th><td><strong>{wk_rms:.4f} m/s²</strong></td></tr>
            </table>
            
            <div class="status-box">
                ISO 2631-1 Comfort Classification: {comfort_str.upper()}
            </div>
        </div>

        <div class="footer">
            This document is auto-generated by the SuspensionLab Enterprise CAE Engine.<br>
            It serves as verifiable validation for internal procurement and engineering sign-off.
        </div>
    </body>
    </html>
    """

    return Response(
        content=html_content,
        media_type="text/html",
        headers={"Content-Disposition": "inline; filename=iso2631_report.html"}
    )
