apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  namespace: suspensionlab-prod
  labels:
    app: suspensionlab
    component: ui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: suspensionlab
      component: ui
  template:
    metadata:
      labels:
        app: suspensionlab
        component: ui
    spec:
      containers:
      - name: ui
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        resources:
{{ toYaml .Values.ui.resources | indent 10 }}
