apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  namespace: suspensionlab-prod
spec:
  selector:
    app: suspensionlab
    component: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
