import datetime
from suspensionlab.physics.quarter_car import QuarterCarParams

def export_quarter_car_to_adams(params: QuarterCarParams, filename: str = "quarter_car_export.adm") -> str:
    """
    Generates a realistic, valid MSC ADAMS (.adm) file for the Quarter Car model.
    """
    import datetime
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    adm_content = f"""! MSC.ADAMS/Solver Dataset
! Generated by SuspensionLab PRO MAX (Enterprise)
! Timestamp: {now}

ADAMS/View model name: Quarter_Car_Rig
!
UNITS/ FORCE=NEWTON, MASS=KILOGRAM, LENGTH=METER, TIME=SECOND
!
!----------------------------------- PARTS -------------------------------------
!
PART/1, GROUND
!
PART/2, MASS={params.m_s}, CM=201, IP=1.0, 1.0, 1.0
! Sprung Mass
!
PART/3, MASS={params.m_u}, CM=301, IP=0.1, 0.1, 0.1
! Unsprung Mass (Wheel Assembly)
!
!---------------------------------- MARKERS ------------------------------------
!
MARKER/201, PART = 2, QP = 0, 0.5, 0
MARKER/301, PART = 3, QP = 0, 0.25, 0
MARKER/101, PART = 1, QP = 0, 0, 0
!
!----------------------------------- JOINTS ------------------------------------
!
JOINT/1, TRANSLATIONAL, I = 201, J = 101
JOINT/2, TRANSLATIONAL, I = 301, J = 101
!
!----------------------------------- FORCES ------------------------------------
!
! Suspension Spring & Damper (Using standard ADAMS SPRINGDAMPER element)
SPRINGDAMPER/1, TRANSLATIONAL, I = 201, J = 301, STIFFNESS_COEFFICIENT = {params.k_w}, DAMPING_COEFFICIENT = {params.c}
!
! Tire Spring
SPRINGDAMPER/2, TRANSLATIONAL, I = 301, J = 101, STIFFNESS_COEFFICIENT = {params.k_t}, DAMPING_COEFFICIENT = 0.0
!
!----------------------------------- RESULTS -----------------------------------
!
REQUEST/1, DISPLACEMENT, I=201, J=101, RM=101
REQUEST/2, ACCELERATION, I=201, J=101, RM=101
!
END
"""
    return adm_content

def export_quarter_car_to_matlab(params: QuarterCarParams) -> str:
    """
    Generates a MATLAB script (.m) that builds the State-Space representation
    of the Quarter Car model for native control system design.
    """
    matlab_content = f"""% SuspensionLab PRO MAX - MATLAB State-Space Exporter
% Generated on: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
% 
% Use this script to load the exact suspension parameters into the MATLAB workspace
% and generate the continuous-time LTI State-Space model (sys_qc).

clear; clc;

%% 1. Vehicle Parameters
m_s = {params.m_s};    % Sprung Mass [kg]
m_u = {params.m_u};     % Unsprung Mass [kg]
k_s = {params.k_s};  % Suspension Spring Rate [N/m]
c   = {params.c};     % Damping Coefficient [Ns/m]
k_t = {params.k_t}; % Tire Stiffness [N/m]
MR  = {params.MR};     % Motion Ratio [-]

% Wheel rate
k_w = k_s * (MR^2);

%% 2. State-Space Matrices
% States x = [z_s; z_u; dz_s; dz_u]
% Input  u = [z_r] (Road Profile Displacement)
% Output y = [z_s; z_u; dz_s; dz_u; ddz_s]

A = [   0,        0,       1,      0;
        0,        0,       0,      1;
     -k_w/m_s,  k_w/m_s, -c/m_s,  c/m_s;
      k_w/m_u, -(k_w+k_t)/m_u, c/m_u, -c/m_u ];

B = [   0;
        0;
        0;
      k_t/m_u ];

C = [ 1, 0, 0, 0;    % Sprung Disp
      0, 1, 0, 0;    % Unsprung Disp
      0, 0, 1, 0;    % Sprung Vel
      0, 0, 0, 1;    % Unsprung Vel
     -k_w/m_s, k_w/m_s, -c/m_s, c/m_s ]; % Sprung Accel

D = [ 0; 0; 0; 0; 0 ];

%% 3. Build LTI System
sys_qc = ss(A, B, C, D);
sys_qc.StateName = {{'z_s', 'z_u', 'dz_s', 'dz_u'}};
sys_qc.InputName = {{'z_r'}};
sys_qc.OutputName = {{'z_s', 'z_u', 'dz_s', 'dz_u', 'ddz_s'}};

disp('✅ Quarter Car LTI System `sys_qc` loaded into workspace successfully.');
bode(sys_qc(5,1)); % Plot Body Accel Transmissibility
title('Bode Plot: Road to Body Acceleration');
"""
    return matlab_content
